theme: minima

# Site settings
title: JohnVanD
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio and Asset showcase from JohnVanD
baseurl: "/JohnVanD" # the subpath of your site, e.g. /blog
url: "https://jayfiraja.github.io/JohnVanD" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
